### PR TITLE
EE-27130 Adding example UAN to match the English

### PR DESCRIPTION
**Pull request by owainrobertsbjss**

### CODE REVIEW

**Comment by zuzak** [comment]
In English we'd avoid using "eg": https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#e, should it be "er enghraifft" instead?

**Comment by owainrobertsbjss** [comment]
> In English we'd avoid using "eg": https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#e, should it be "er enghraifft" instead?

Makes sense. I'm going to merge the current change as it's consistent with the English and matches the JIRA but I've put it to the BAs that they may want to change it.

**Comment by owainrobertsbjss** [comment]
Using admin privileges to merge as this service isn't released yet and nobody on the team speaks Welsh.

**Comment by DrewCrook** [comment]
Were using e.e.

**Pull request merged**
